GET http://localhost:8880/ebook/list?page=1&size=1001
Accept: application/json
###
GET http://localhost:8880/doc/all/1
Accept: application/json

###
GET http://localhost:8880/save
Accept: application/json